logging:
  level:
    vn.com.buaansach: DEBUG
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bas_prod?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: admin
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    drop-first: false
    enabled: true
