# common config for both dev and prod environment
spring:
  application:
    name: buaansach
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: mailservice.pms@gmail.com
    password: Bingo102
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
audit-events:
  retention-period: 30
websocket:
  allowed-origin: '*'
app:
  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: Ka7xdBsrLXVkEeMRYXsfl0b3Z3iSjiUO8H9cIMRmdAiwNCF5R8/eN/11jVlI7sHLgMXG2gTTTKlMhtJq7U6pSg==
    # Token is valid 24 hours
    token-time: 86400
    # Token valid for 7 days with remember me
    token-time-for-remember: 604800
  upload-dir: 'D:/bas/storage/'
  server-domain: 'http://localhost'
  mail:
    enable: true
    from: mailservice.pms@gmail.com
    send-creation-mail: false
    client-base-url: 'http://localhost:3000'
