logging:
  level:
    vn.com.buaansach: DEBUG
server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/bas_staging?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: buaansach_staging
    password: Plain$ecuredText4bas_staging@2020!
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    drop-first: false
    enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: noreply.ductran.tech@gmail.com
    password: Bingo102
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
app:
  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    base64-secret: Ka7xdBsrLXVkEeMRYXsfl0b3Z3iSjiUO8H9cIMRmdAiwNCF5R8/eN/11jVlI7sHLgMXG2gTTTKlMhtJq7U6pSg==
    # Token is valid 24 hours
    token-time: 86400
    # Token valid for 7 days with remember me
    token-time-for-remember: 604800
  upload-dir: '/bas/storage/'
  server-domain: 'https://api.ductran.tech'
  mail:
    enable: true
    from: noreply.ductran.tech@gmail.com
    send-creation-mail: false
    cms-ui-url: 'https://pos.ductran.tech'
