# common config for both dev and prod environment
spring:
  application:
    name: buaansach
  profiles:
    active: dev
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
audit-events:
  retention-period: 30
websocket:
  allowed-origin: '*'
