version: 2.1
jobs:
  deploy-staging:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            TAG=staging
            docker build -t $DOCKER_REGISTRY/backend:$TAG .
            docker push $DOCKER_REGISTRY/backend:$TAG

      - run:
          name: Deploy
          command: |
            TAG=staging
            # ssh root@$STAGING_DOMAIN
            ssh root@$DOCKER_REGISTRY "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY && docker pull $DOCKER_REGISTRY/backend:$TAG"
workflows:
  build-and-test:
    jobs:
      # - build
      - deploy-staging
