version: 2.1
jobs:
  deploy-staging:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            TAG=staging
            docker build -t $DOCKER_REGISTRY/backend:$TAG .
            docker push $DOCKER_REGISTRY/backend:$TAG

      - run:
          name: Deploy
          command: |
            TAG=staging
            # ssh root@$STAGING_DOMAIN
            ssh root@$DOCKER_REGISTRY "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY && docker pull $DOCKER_REGISTRY/backend:$TAG && cd /root/app/buaansach-config-ui && docker-compose -f docker-compose-staging.yml up -d --force-recreate --build server"

  build-production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            TAG=production
            docker build -t $DOCKER_REGISTRY/backend:$TAG .
            docker push $DOCKER_REGISTRY/backend:$TAG

  deploy-production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Deploy
          command: ssh-keyscan $PRODUCTION_DOMAIN >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            TAG=production
            ssh root@$PRODUCTION_DOMAIN "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY && docker pull $DOCKER_REGISTRY/backend:$TAG && cd /root/app/buaansach-config-ui && docker-compose -f docker-compose-production.yml up -d --force-recreate --build server"
workflows:
  build-and-deploy:
    jobs:
      # - build
      # - build
      # - deploy-staging
      # - hold:
      #     type: approval
      #     requires:
      #       - deploy-staging
      - build-production
      - deploy-production:
          requires:
            - build-production
        # requires:
        #   - hold
