# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: docker build --pull --rm -f "Dockerfile" -t buaansachserver:latest "."