version: 2.1
jobs:
  build-staging:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            TAG=staging
            docker build -t $DOCKER_USER/buaansach:server-staging .
            docker push $DOCKER_USER/buaansach:server-staging

  build-production:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            TAG=production
            docker build -t $DOCKER_USER/buaansach:server-production .
            docker push $DOCKER_USER/buaansach:server-production

workflows:
  build-and-push-image:
    jobs:
      # - build
      - build-staging:
          filters:
            branches:
              only:
                - staging
      - build-production:
          filters:
            branches:
              only:
                - master
