version: 2.1
jobs:
  build-server:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build docker
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            TAG=staging
            docker build -t $DOCKER_USER/buaansach:server .
            docker push $DOCKER_USER/buaansach:server

workflows:
  build:
    jobs:
      # - build
      - build-server:
          filters:
            branches:
              only:
                - master
